apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-ingress
  namespace: bookstore
spec:
  rules:
    - host: bookstore.local
      http:
        paths:
          - path: /api/admin/cluster
            pathType: Prefix
            backend:
              service:
                name: monitoring-backend-service
                port:
                  number: 8000
          - path: /api/admin
            pathType: Prefix
            backend:
              service:
                name: admin-backend-service
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: public-backend-service
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
# You may need to enable an ingress controller (for example: minikube addons enable ingress).
